/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectType = IDL.Variant({
  'interior' : IDL.Null,
  'commercial' : IDL.Null,
  'residential' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactInquiry = IDL.Record({
  'projectType' : ProjectType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'budgetRange' : IDL.Text,
});
export const ProjectStatus = IDL.Variant({
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const FeaturedProject = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'name' : IDL.Text,
  'shortDescription' : IDL.Text,
  'ptype' : ProjectType,
  'location' : IDL.Text,
});
export const PropertyListing = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'area' : IDL.Nat,
  'name' : IDL.Text,
  'priceRange' : IDL.Text,
  'shortDescription' : IDL.Text,
  'ptype' : ProjectType,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(FeaturedProject)], ['query']),
  'getListingById' : IDL.Func([IDL.Nat], [PropertyListing], ['query']),
  'getListings' : IDL.Func(
      [IDL.Opt(ProjectType), IDL.Opt(ProjectStatus)],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getProjectsByType' : IDL.Func(
      [ProjectType],
      [IDL.Vec(FeaturedProject)],
      ['query'],
    ),
  'init' : IDL.Func([], [], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ProjectType, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectType = IDL.Variant({
    'interior' : IDL.Null,
    'commercial' : IDL.Null,
    'residential' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactInquiry = IDL.Record({
    'projectType' : ProjectType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'budgetRange' : IDL.Text,
  });
  const ProjectStatus = IDL.Variant({
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const FeaturedProject = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'name' : IDL.Text,
    'shortDescription' : IDL.Text,
    'ptype' : ProjectType,
    'location' : IDL.Text,
  });
  const PropertyListing = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'area' : IDL.Nat,
    'name' : IDL.Text,
    'priceRange' : IDL.Text,
    'shortDescription' : IDL.Text,
    'ptype' : ProjectType,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(FeaturedProject)], ['query']),
    'getListingById' : IDL.Func([IDL.Nat], [PropertyListing], ['query']),
    'getListings' : IDL.Func(
        [IDL.Opt(ProjectType), IDL.Opt(ProjectStatus)],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getProjectsByType' : IDL.Func(
        [ProjectType],
        [IDL.Vec(FeaturedProject)],
        ['query'],
      ),
    'init' : IDL.Func([], [], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ProjectType, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };