/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PropertyListing {
    id: bigint;
    status: ProjectStatus;
    area: bigint;
    name: string;
    priceRange: string;
    shortDescription: string;
    ptype: ProjectType;
    location: string;
}
export type Time = bigint;
export interface FeaturedProject {
    id: bigint;
    status: ProjectStatus;
    name: string;
    shortDescription: string;
    ptype: ProjectType;
    location: string;
}
export interface ContactInquiry {
    projectType: ProjectType;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
    budgetRange: string;
}
export enum ProjectStatus {
    completed = "completed",
    ongoing = "ongoing"
}
export enum ProjectType {
    interior = "interior",
    commercial = "commercial",
    residential = "residential"
}
export interface backendInterface {
    getAllInquiries(): Promise<Array<ContactInquiry>>;
    getAllProjects(): Promise<Array<FeaturedProject>>;
    getListingById(id: bigint): Promise<PropertyListing>;
    getListings(filterType: ProjectType | null, filterStatus: ProjectStatus | null): Promise<Array<PropertyListing>>;
    getProjectsByType(filterType: ProjectType): Promise<Array<FeaturedProject>>;
    init(): Promise<void>;
    submitInquiry(name: string, phone: string, email: string, projectType: ProjectType, budgetRange: string, message: string): Promise<void>;
}
import type { ContactInquiry as _ContactInquiry, FeaturedProject as _FeaturedProject, ProjectStatus as _ProjectStatus, ProjectType as _ProjectType, PropertyListing as _PropertyListing, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllInquiries(): Promise<Array<ContactInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProjects(): Promise<Array<FeaturedProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingById(arg0: bigint): Promise<PropertyListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingById(arg0);
                return from_candid_PropertyListing_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingById(arg0);
            return from_candid_PropertyListing_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListings(arg0: ProjectType | null, arg1: ProjectStatus | null): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListings(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListings(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectsByType(arg0: ProjectType): Promise<Array<FeaturedProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByType(to_candid_ProjectType_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByType(to_candid_ProjectType_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async init(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.init();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.init();
            return result;
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: ProjectType, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, to_candid_ProjectType_n14(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, to_candid_ProjectType_n14(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
}
function from_candid_ContactInquiry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactInquiry): ContactInquiry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_FeaturedProject_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeaturedProject): FeaturedProject {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectType): ProjectType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyListing_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyListing): PropertyListing {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProjectStatus;
    area: bigint;
    name: string;
    priceRange: string;
    shortDescription: string;
    ptype: _ProjectType;
    location: string;
}): {
    id: bigint;
    status: ProjectStatus;
    area: bigint;
    name: string;
    priceRange: string;
    shortDescription: string;
    ptype: ProjectType;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n9(_uploadFile, _downloadFile, value.status),
        area: value.area,
        name: value.name,
        priceRange: value.priceRange,
        shortDescription: value.shortDescription,
        ptype: from_candid_ProjectType_n4(_uploadFile, _downloadFile, value.ptype),
        location: value.location
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projectType: _ProjectType;
    name: string;
    email: string;
    message: string;
    timestamp: _Time;
    phone: string;
    budgetRange: string;
}): {
    projectType: ProjectType;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
    budgetRange: string;
} {
    return {
        projectType: from_candid_ProjectType_n4(_uploadFile, _downloadFile, value.projectType),
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone,
        budgetRange: value.budgetRange
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProjectStatus;
    name: string;
    shortDescription: string;
    ptype: _ProjectType;
    location: string;
}): {
    id: bigint;
    status: ProjectStatus;
    name: string;
    shortDescription: string;
    ptype: ProjectType;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n9(_uploadFile, _downloadFile, value.status),
        name: value.name,
        shortDescription: value.shortDescription,
        ptype: from_candid_ProjectType_n4(_uploadFile, _downloadFile, value.ptype),
        location: value.location
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    ongoing: null;
}): ProjectStatus {
    return "completed" in value ? ProjectStatus.completed : "ongoing" in value ? ProjectStatus.ongoing : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    interior: null;
} | {
    commercial: null;
} | {
    residential: null;
}): ProjectType {
    return "interior" in value ? ProjectType.interior : "commercial" in value ? ProjectType.commercial : "residential" in value ? ProjectType.residential : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactInquiry>): Array<ContactInquiry> {
    return value.map((x)=>from_candid_ContactInquiry_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PropertyListing>): Array<PropertyListing> {
    return value.map((x)=>from_candid_PropertyListing_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeaturedProject>): Array<FeaturedProject> {
    return value.map((x)=>from_candid_FeaturedProject_n7(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectType): _ProjectType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectType | null): [] | [_ProjectType] {
    return value === null ? candid_none() : candid_some(to_candid_ProjectType_n14(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus | null): [] | [_ProjectStatus] {
    return value === null ? candid_none() : candid_some(to_candid_ProjectStatus_n17(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectType): {
    interior: null;
} | {
    commercial: null;
} | {
    residential: null;
} {
    return value == ProjectType.interior ? {
        interior: null
    } : value == ProjectType.commercial ? {
        commercial: null
    } : value == ProjectType.residential ? {
        residential: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    completed: null;
} | {
    ongoing: null;
} {
    return value == ProjectStatus.completed ? {
        completed: null
    } : value == ProjectStatus.ongoing ? {
        ongoing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
